# Metadata for the classic-plugin
plugin:
    # Global plugin attributes
    type: system                    # plugin type (gateway, interface, protocol, system, web)
    description:
        de: 'Funktionalität zum Abarbeiten von Sequencen'
        en: 'Functionality to allow processing of sequences'
#    maintainer:
#    tester:
#    keywords: kwd1 kwd2            # keywords, where applicable
#    documentation: https://github.com/smarthomeNG/plugins/sequencer/README.md
#    support: 

    version: 0.0.1                 # Plugin version
    sh_minversion: 1.3c            # minimum shNG version to use this plugin
#    sh_maxversion:                 # maximum shNG version to use this plugin (leave empty if latest)
    multi_instance: False
    classname: Sequencer           # class containing the plugin

parameters:
    # Definition of parameters to be configured in etc/plugin.yaml
